name: build-app

on: [push]

jobs:
  build-executable:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run:  python3 -m pip install pyinstaller Pillow tk

      - name: Install project deps
        run: python3 -m pip install .

      - name: Package pyinstaller
        run: pyinstaller src/rclone_decrypt/gui.py --onefile --windowed --additional-hooks-dir=. --icon=docs/imgs/rd.ico --name rclone-decrypt

      - uses: actions/upload-artifact@v3
        with:
          name: rclone-decrypt-gui
          path: dist/rclone-decrypt.app
